using MyBlog.Data;
using MyBlog.Services;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

// ----------------------------
// Cloud Run Port Binding
// ----------------------------
var port = Environment.GetEnvironmentVariable("PORT") ?? "8080";
builder.WebHost.UseUrls($"http://0.0.0.0:{port}");

// ----------------------------
// Services
// ----------------------------
builder.Services.AddControllersWithViews();

builder.Services.AddSingleton<BlogService>();
builder.Services.AddScoped<CommentService>();
builder.Services.AddScoped<LikeService>();

if (builder.Environment.IsDevelopment())
{
    builder.Services.AddDbContext<BlogDbContext>(options =>
        options.UseInMemoryDatabase("BlogDevDb"));
}
else
{
    var connectionString = Environment.GetEnvironmentVariable("DefaultConnection");
    builder.Services.AddDbContext<BlogDbContext>(options =>
        options.UseNpgsql(connectionString));
}

builder.Services.AddRouting(options => options.LowercaseUrls = true);

var app = builder.Build();

try
{
    using var scope = app.Services.CreateScope();
    var db = scope.ServiceProvider.GetRequiredService<BlogDbContext>();
    db.Database.Migrate();

    if (db.Database.IsNpgsql())
    {
        db.Database.ExecuteSqlRaw("""
                                  ALTER TABLE "Comments"
                                  ADD COLUMN IF NOT EXISTS "ParentCommentId" integer;
                                  """);

        db.Database.ExecuteSqlRaw("""
                                  CREATE INDEX IF NOT EXISTS "IX_Comments_ParentCommentId"
                                  ON "Comments" ("ParentCommentId");
                                  """);

        db.Database.ExecuteSqlRaw("""
                                  CREATE TABLE IF NOT EXISTS "PostLikes" (
                                      "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      "PostId" text NOT NULL,
                                      "VisitorId" text NOT NULL,
                                      "LikedAt" timestamp with time zone NOT NULL
                                  );
                                  """);

        db.Database.ExecuteSqlRaw("""
                                  CREATE UNIQUE INDEX IF NOT EXISTS "IX_PostLikes_PostId_VisitorId"
                                  ON "PostLikes" ("PostId", "VisitorId");
                                  """);

        db.Database.ExecuteSqlRaw("""
                                  CREATE TABLE IF NOT EXISTS "CommentLikes" (
                                      "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      "CommentId" integer NOT NULL REFERENCES "Comments" ("Id") ON DELETE CASCADE,
                                      "VisitorId" text NOT NULL,
                                      "LikedAt" timestamp with time zone NOT NULL
                                  );
                                  """);

        db.Database.ExecuteSqlRaw("""
                                  CREATE UNIQUE INDEX IF NOT EXISTS "IX_CommentLikes_CommentId_VisitorId"
                                  ON "CommentLikes" ("CommentId", "VisitorId");
                                  """);
    }
}
catch (Exception ex)
{
    Console.WriteLine($"Warning: DB not ready yet: {ex.Message}");
}


// ----------------------------
// Middleware
// ----------------------------
app.UseStaticFiles();
app.UseRouting();
app.UseAuthorization();

// ----------------------------
// Routes
// ----------------------------
app.MapControllerRoute(
    name: "blogPost",
    pattern: "blog/{slug?}",
    defaults: new { controller = "Blog", action = "Post" });

app.MapControllerRoute(
    name: "blogIndex",
    pattern: "blog",
    defaults: new { controller = "Blog", action = "Index" });

app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");

app.UseDeveloperExceptionPage();

app.Run();
